//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiskyClub.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    internal partial class TastingNote
    {
    	public int TastingNoteId { get; set; }
    	public int WhiskyId { get; set; }
    	public int MemberId { get; set; }
    	public string Comment { get; set; }
    	public byte[] Image { get; set; }
    	public byte[] Version { get; set; }
    	public System.DateTime InsertedDate { get; set; }
    	public System.DateTime UpdatedDate { get; set; }
    
    	public virtual Member Member { get; set; }
    	public virtual Whisky Whisky { get; set; }
    }
}
