//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiskyClub.DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Host
    {
    	public Host()
    	{
    		this.Events = new HashSet<Event>();
    	}
    
    	public int HostId { get; set; }
    	public string Name { get; set; }
    	public byte[] Version { get; set; }
    	public System.DateTime InsertedDate { get; set; }
    	public System.DateTime UpdatedDate { get; set; }
    
    	public virtual ICollection<Event> Events { get; set; }
    }
}
